### ISSUE TITLE
Scrolling a very big image list is laggy

### ISSUE THREAD

**Issue by ngyikp** [ImageOptim/ImageOptim#141] opened 2016-03-26 03:37 UTC
I optimised an assets folder with about ~3600 images, and scrolling the list is very laggy even after the optimisation is done.

<s>Video: https://dl.dropboxusercontent.com/u/1286251/images/imageoptim%20lag.mp4</s>

ImageOptim version 1.6.1
Mac OS 10.11.4

**Comment by pornel** [comment] 2016-06-02 19:29
Yes, I can confirm this. There's some awful performance regression in OS X that makes drawing of images in the list *incredibly* slow. System spends 99% of time in the `argb32_image_mark_argb32` function, burning cycles.

I'm not sure what to do about it from ImageOptim's perspective, because I'm only using very high-level concepts like `imageNamed` and image table cell.

**Comment by MiroHofo** [comment] 2017-04-26 06:29
Could something be done about this? 
UI is very very laggy, it is pain to use it, sort it, scroll. There has to be a way how to optimize it, please :)

**Comment by MiroHofo** [comment] 2017-04-29 08:41
Hey guys!
I have found what is causing issue and got a fix. It was all caused by opacity at loupe button, so whan I removed it, scrolling, sorting, selecting items is fast as lightning. Modified code in RevealButtonCell.m (if switch can be removed completely):
`float opacity = iMouseHoveredInInfoButton ? 1.0f : ([self isHighlighted] ? 1.0f : 1.0f);
    [image drawInRect:infoButtonRect fromRect:NSZeroRect operation:NSCompositeSourceOver fraction:opacity respectFlipped:YES hints:nil];
}`
First time using Xcode and git and don't know how to submit this. @pornel could you please submit this fix and build new version?

[RevealButtonCell.m.zip](https://github.com/ImageOptim/ImageOptim/files/966002/RevealButtonCell.m.zip)

**Comment by pornel** [comment] 2017-04-29 13:14
Oh, brilliant! I wrongly assumed that image rendering was from the status image column, and didn't think of the loupe.

Hopefully fixed in 6ee2893d511e531f78d8b868a582e5e60f4a6792

**Closed** 2017-05-29 20:51 UTC
